// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqOf59CvMRqPCkO6ahIG3JoiEokf4dWY',
    appId: '1:471548650694:web:5d905e18fbfb0eabc223c7',
    messagingSenderId: '471548650694',
    projectId: 'flutterrestaurante-eddd3',
    authDomain: 'flutterrestaurante-eddd3.firebaseapp.com',
    storageBucket: 'flutterrestaurante-eddd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnp20iPz8oQknGcEUGPq8IAg1gLVGvKFk',
    appId: '1:471548650694:android:dd9b129b529066a3c223c7',
    messagingSenderId: '471548650694',
    projectId: 'flutterrestaurante-eddd3',
    storageBucket: 'flutterrestaurante-eddd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmfxzv95y-7s033tt1TzLKjy0eHjK_yTQ',
    appId: '1:471548650694:ios:b92da45555804f6ac223c7',
    messagingSenderId: '471548650694',
    projectId: 'flutterrestaurante-eddd3',
    storageBucket: 'flutterrestaurante-eddd3.firebasestorage.app',
    iosClientId: '471548650694-tllfd3s1qsb55tu025q1uol2fcvlhk7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.restauranteFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmfxzv95y-7s033tt1TzLKjy0eHjK_yTQ',
    appId: '1:471548650694:ios:b92da45555804f6ac223c7',
    messagingSenderId: '471548650694',
    projectId: 'flutterrestaurante-eddd3',
    storageBucket: 'flutterrestaurante-eddd3.firebasestorage.app',
    iosClientId: '471548650694-tllfd3s1qsb55tu025q1uol2fcvlhk7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.restauranteFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfqOf59CvMRqPCkO6ahIG3JoiEokf4dWY',
    appId: '1:471548650694:web:757c9c0dcbd3e90bc223c7',
    messagingSenderId: '471548650694',
    projectId: 'flutterrestaurante-eddd3',
    authDomain: 'flutterrestaurante-eddd3.firebaseapp.com',
    storageBucket: 'flutterrestaurante-eddd3.firebasestorage.app',
  );
}
